# Generated by Django 2.2 on 2020-09-16 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('publish_date', models.DateTimeField(verbose_name='publish date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='last update date')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
